name: sonatype
on:
  push:
    branches: [master]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - uses: olafurpg/setup-gpg@v2
      - name: Publish
        run: |
          git ls-remote --get-url origin
          sbt test ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      - name: github-pages
        run: |
          sbt clean makeSite
          cd target/site
          git init 
          git add . 
          git commit -m "update site"
          git push --force https://pityka:${{secrets.GITHUB_TOKEN}}@github.com/pityka/saddle master:gh-pages
          